CREATE DATABASE LANHOUSE_ROCKETZ

USE LANHOUSE_ROCKETZ

CREATE TABLE USUARIO(
	ID INT PRIMARY KEY IDENTITY,
	EMAIL VARCHAR(150) UNIQUE NOT NULL,			
	SENHA VARCHAR(150) NOT NULL
)

CREATE TABLE DEFEITO(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE TIPO_EQUIPAMENTO(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE REGISTRO_DEFEITO(
	ID INT PRIMARY KEY IDENTITY,
	DATA_DEFEITO DATETIME NOT NULL,
	TIPO_EQUIPAMENTO_ID INT FOREIGN KEY REFERENCES TIPO_EQUIPAMENTO(ID),
	DEFEITO_ID INT FOREIGN KEY REFERENCES DEFEITO(ID),
	OBSERVACAO VARCHAR(255) NOT NULL
)